name_list=["zhang yue","kong jun","zhang zhe"]
print(len(name_list))
print(name_list[0])
print(name_list[len(name_list)-1])
name_list.append("xiaokong")
print(name_list)
name_list.remove("zhang zhe")
print(name_list)
name_list.insert(2,"sunlaoshi")
print(name_list)